baseURL = "/"
title = "Beyond The Software"
languageCode = "en-us"
defaultContentLanguage = "en"
paginate = "7"
theme = "spectral"

[params]
fancyTitle = "Beyond the Software" # title for frontpage, may include image
copyright = "Darrin Braun"
description = 'It is about the people who run your business everyday.<br /> We go beyond the software, empowering your team <br/ > to efficiently and profitably operate the business.'
startbuttonText = "Request Consultation"
startbuttonLink = "#contact"
body_is_markdown = true
#custom_css = "foo.css"
#images = ["path_to_social_image_for_link_previews.jpg"]

[[params.menu.main]]
url = '/'
title = "Home"
#un-comment + edit later
#[[params.menu.main]]
#url = '/Posts/index.html'
#title = "Posts"
[[params.menu.main]]
url = 'https://www.linkedin.com/in/darrinbraun/'
title = "About"

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

#delete this  | and add all the code
#             v
[params.one]
enable = true
title = 'Our Proccess'
body = '''
We work with key stakeholders to understand the current processes in your company. With this understanding and buy in, we develop a Strategy, communicate it, and execute on it. The process is designed to bring together your people, processees, and technology. The benefit is happier employees and clients, while improving the financial health an longevity of your business.
'''

[params.two]
enable = true
title = 'Aspire Corner'
body = '''
..
'''

[params.contact]
enable = true
title = "Contact"
body = '''
<script charset="utf-8" type="text/javascript" src="//js.hsforms.net/forms/v2.js"></script>
<script>
  hbspt.forms.create({
    region: "na1",
    portalId: "22357356",
    formId: "995d2ce1-363c-4a9d-b9b1-39f27b4bee5f"
  });
</script>
'''
phone = "+12622366716"
address = "Pewaukee, Wi USA"
email = "darrin@beyondthesoftware.com"
subject = "New Submission!"
plain = false

[params.social]
twitter = ""
facebook = ""
instagram = ""
dribble = ""
linkedin = ""
# language specific options

[languages.en]
weight = 0
languageName = "English"
